### ISSUE TITLE
SampleQuizPage fix

### ISSUE THREAD

**Issue by tanvirraihanislam** [sam-c14/Quiz-App#10]
In the 'Sample Quiz' section, the navbar is getting merged with the Sample Quiz body. The contents of the sample quiz is coming under navbar

**Comment by sam-c14** [comment]
> In the 'Sample Quiz' section, the navbar is getting merged with the Sample Quiz body. The contents of the sample quiz is coming under navbar

Okay can you ssuggest any solution sir

**Comment by tanvirraihanislam** [comment]
Hi @sam-c14, I have added padding to the page. Please check my pull request and let me know if you want me to change anything in it. If not, I would request you merge it so that I can move on to further contributions to this project.
